// pageRegistry.ts — single source of truth for proto pages
// Agents MUST read notes[] before working on any page.

export type NavVariant = 'none' | 'public' | 'auth' | 'client' | 'admin';
export type PageGroup = 'Overview' | 'Public' | 'Auth' | 'Dashboard' | 'Commissioner' | 'Admin' | 'Brand';

export interface PageNote {
  date: string;
  state?: string;
  text: string;
}

export interface PageEntry {
  id: string;
  title: string;
  group: PageGroup;
  route: string;
  stateCount: number;
  nav: NavVariant;
  activeTab?: string;
  navFrom?: string[];   // page IDs that navigate TO this page
  navTo?: string[];     // page IDs this page navigates TO
  qaCycles?: number;   // how many proto+proto-check cycles completed (target: 5)
  qaScore?: number;    // last QC score (0-12)
  notes?: PageNote[];
}

// QA CYCLE TRACKING:
// qaCycles tracks how many times proto was created/improved + proto-check passed (score >= 9).
// Target: 5 cycles per page before manual review by Sergei.
// Status: [ ] = no qaCycles | [proto] = qaCycles 1-4 | [review] = qaCycles >= 5

export const pages: PageEntry[] = [
  // ─── Overview & Brand ──────────────────────────────────────────────────────
  {
    id: 'overview',
    title: 'Project Overview',
    group: 'Overview',
    route: '/proto/states/overview',
    stateCount: 1,
    nav: 'none',
  },
  {
    id: 'brand',
    title: 'Brand & Styles',
    group: 'Brand',
    route: '/proto/states/brand',
    stateCount: 1,
    nav: 'none',
  },

  // ─── Public ────────────────────────────────────────────────────────────────
  {
    id: 'landing',
    title: 'Landing',
    group: 'Public',
    route: '/',
    stateCount: 3,
    nav: 'public',
    navTo: ['tournaments', 'org-apply', 'login', 'commissars', 'ratings'],
    qaCycles: 3, qaScore: 12,
    notes: [
      {
        date: '2026-04-10',
        text: 'All /proto/states/* must be accessible without auth. app/proto/_layout.tsx is a clean Stack — no auth guard, no Redirect.',
      },
      {
        date: '2026-04-09',
        text: 'Cycle 2: Added working navigation (router.push) to all CTAs/links/footer/cards. Unique picsum seeds per tournament. Rankings limited to top 5. All navTo destinations wired.',
      },
    ],
  },
  {
    id: 'tournaments',
    title: 'Tournament Catalog',
    group: 'Public',
    route: '/tournaments',
    stateCount: 4,
    nav: 'public',
    navFrom: ['landing', 'dashboard', 'watchlist'],
    navTo: ['tournament-detail'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-detail',
    title: 'Tournament Detail',
    group: 'Public',
    route: '/tournaments/:id',
    stateCount: 9,
    nav: 'public',
    navFrom: ['tournaments', 'watchlist', 'dashboard', 'notifications'],
    navTo: ['login', 'payment', 'tournament-schedule', 'tournament-announcements', 'commissar-profile'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'commissars',
    title: 'Commissar Catalog',
    group: 'Public',
    route: '/commissars',
    stateCount: 5,
    nav: 'public',
    navFrom: ['landing'],
    navTo: ['commissar-profile'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'commissar-profile',
    title: 'Commissar Public Profile',
    group: 'Public',
    route: '/commissars/:id',
    stateCount: 3,
    nav: 'public',
    navFrom: ['commissars', 'tournament-detail'],
    navTo: [],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'user-profile',
    title: 'Public User Profile',
    group: 'Public',
    route: '/users/:id',
    stateCount: 3,
    nav: 'public',
    navFrom: ['ratings', 'tournament-detail'],
    navTo: ['elo-history'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'ratings',
    title: 'Rating List',
    group: 'Public',
    route: '/ratings',
    stateCount: 4,
    nav: 'public',
    navFrom: ['landing'],
    navTo: ['elo-history', 'user-profile'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'elo-history',
    title: 'ELO Rating History',
    group: 'Public',
    route: '/ratings/history',
    stateCount: 5,
    nav: 'public',
    navFrom: ['ratings', 'user-profile'],
    navTo: ['tournaments'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'org-apply',
    title: 'Organization Apply',
    group: 'Public',
    route: '/organizations/apply',
    stateCount: 5,
    nav: 'public',
    navFrom: ['landing'],
    navTo: ['landing'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'cert-verify',
    title: 'Certificate Verify',
    group: 'Public',
    route: '/verify/:id',
    stateCount: 4,
    nav: 'public',
    navFrom: [],
    navTo: ['tournament-detail'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'payment-success',
    title: 'Payment Success',
    group: 'Public',
    route: '/payment-success',
    stateCount: 1,
    nav: 'none',
    navFrom: ['payment'],
    navTo: ['my-registrations', 'tournament-detail'],
    qaCycles: 2, qaScore: 12,
  },

  // ─── Auth ──────────────────────────────────────────────────────────────────
  {
    id: 'login',
    title: 'Email Login',
    group: 'Auth',
    route: '/(auth)/login',
    stateCount: 5,
    nav: 'auth',
    navFrom: ['tournament-detail', 'landing'],
    navTo: ['otp'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'otp',
    title: 'OTP Verification',
    group: 'Auth',
    route: '/(auth)/otp',
    stateCount: 6,
    nav: 'auth',
    navFrom: ['login'],
    navTo: ['dashboard'],
    qaCycles: 2, qaScore: 12,
  },

  // ─── Dashboard ─────────────────────────────────────────────────────────────
  {
    id: 'dashboard',
    title: 'Dashboard Home',
    group: 'Dashboard',
    route: '/(dashboard)/',
    stateCount: 3,
    nav: 'client',
    navFrom: ['otp'],
    navTo: ['my-registrations', 'tournaments', 'watchlist', 'notifications', 'commissioner-cabinet'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'profile',
    title: 'Profile Settings',
    group: 'Dashboard',
    route: '/(dashboard)/profile',
    stateCount: 5,
    nav: 'client',
    navFrom: ['dashboard'],
    navTo: [],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'my-registrations',
    title: 'My Registrations',
    group: 'Dashboard',
    route: '/(dashboard)/my-registrations',
    stateCount: 4,
    nav: 'client',
    navFrom: ['dashboard', 'payment-success'],
    navTo: ['tournament-detail'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'watchlist',
    title: 'Watchlist',
    group: 'Dashboard',
    route: '/(dashboard)/watchlist',
    stateCount: 4,
    nav: 'client',
    navFrom: ['dashboard'],
    navTo: ['tournaments', 'payment'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'notifications',
    title: 'Notifications',
    group: 'Dashboard',
    route: '/notifications',
    stateCount: 4,
    nav: 'client',
    navFrom: ['dashboard'],
    navTo: ['tournament-detail', 'my-registrations'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'payment',
    title: 'Payment',
    group: 'Dashboard',
    route: '/(dashboard)/payment/:id',
    stateCount: 4,
    nav: 'client',
    navFrom: ['tournament-detail', 'watchlist'],
    navTo: ['payment-success'],
    qaCycles: 2, qaScore: 12,
  },

  // ─── Commissioner ──────────────────────────────────────────────────────────
  {
    id: 'commissioner-cabinet',
    title: 'Commissioner Cabinet',
    group: 'Commissioner',
    route: '/(dashboard)/commissioner',
    stateCount: 3,
    nav: 'client',
    navFrom: ['dashboard'],
    navTo: ['create-tournament', 'my-tournaments', 'commissioner-edit'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'commissioner-edit',
    title: 'Commissioner Profile Edit',
    group: 'Commissioner',
    route: '/(dashboard)/commissioner/edit',
    stateCount: 4,
    nav: 'client',
    navFrom: ['commissioner-cabinet'],
    navTo: ['commissioner-cabinet'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'my-tournaments',
    title: 'My Tournaments',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/manage',
    stateCount: 4,
    nav: 'client',
    navFrom: ['commissioner-cabinet'],
    navTo: ['tournament-hub', 'create-tournament'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'create-tournament',
    title: 'Create Tournament',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/create',
    stateCount: 4,
    nav: 'client',
    navFrom: ['commissioner-cabinet', 'my-tournaments'],
    navTo: ['tournament-hub'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-hub',
    title: 'Tournament Management Hub',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/:id/hub',
    stateCount: 3,
    nav: 'client',
    navFrom: ['my-tournaments', 'create-tournament'],
    navTo: ['tournament-registrations', 'tournament-rounds', 'tournament-results', 'tournament-photos', 'tournament-announcements', 'tournament-edit'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-edit',
    title: 'Tournament Edit',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/:id/edit',
    stateCount: 5,
    nav: 'client',
    navFrom: ['tournament-hub'],
    navTo: ['tournament-hub'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-registrations',
    title: 'Tournament Registrations',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/:id/registrations',
    stateCount: 5,
    nav: 'client',
    navFrom: ['tournament-hub'],
    navTo: ['tournament-hub'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-results',
    title: 'Tournament Results',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/:id/results',
    stateCount: 5,
    nav: 'client',
    navFrom: ['tournament-hub'],
    navTo: ['tournament-hub'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-photos',
    title: 'Tournament Photos',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/:id/photos',
    stateCount: 5,
    nav: 'client',
    navFrom: ['tournament-hub'],
    navTo: ['tournament-hub'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-rounds',
    title: 'Tournament Rounds',
    group: 'Commissioner',
    route: '/(dashboard)/tournaments/:id/rounds',
    stateCount: 4,
    nav: 'client',
    navFrom: ['tournament-hub'],
    navTo: ['tournament-results', 'tournament-hub'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-schedule',
    title: 'Tournament Schedule',
    group: 'Commissioner',
    route: '/tournaments/:id/schedule',
    stateCount: 4,
    nav: 'public',
    navFrom: ['tournament-detail'],
    navTo: ['tournament-detail'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'tournament-announcements',
    title: 'Tournament Announcements',
    group: 'Commissioner',
    route: '/tournaments/:id/announcements',
    stateCount: 4,
    nav: 'public',
    navFrom: ['tournament-detail', 'tournament-hub'],
    navTo: ['tournament-detail'],
    qaCycles: 2, qaScore: 12,
  },

  // ─── Admin ─────────────────────────────────────────────────────────────────
  {
    id: 'admin',
    title: 'Admin Dashboard',
    group: 'Admin',
    route: '/(admin)/',
    stateCount: 3,
    nav: 'admin',
    navTo: ['admin-users', 'admin-tournaments', 'admin-organizations', 'admin-moderation', 'admin-finances', 'admin-disputes', 'admin-webhooks'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-users',
    title: 'Admin Users',
    group: 'Admin',
    route: '/(admin)/users',
    stateCount: 4,
    nav: 'admin',
    navFrom: ['admin'],
    navTo: ['admin'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-tournaments',
    title: 'Admin Tournaments',
    group: 'Admin',
    route: '/(admin)/tournaments',
    stateCount: 5,
    nav: 'admin',
    navFrom: ['admin'],
    navTo: ['admin'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-organizations',
    title: 'Admin Organizations',
    group: 'Admin',
    route: '/(admin)/organizations',
    stateCount: 4,
    nav: 'admin',
    navFrom: ['admin'],
    navTo: ['admin'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-moderation',
    title: 'Admin Moderation',
    group: 'Admin',
    route: '/(admin)/moderation',
    stateCount: 4,
    nav: 'admin',
    navFrom: ['admin', 'admin-disputes'],
    navTo: ['admin-disputes'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-finances',
    title: 'Admin Finances',
    group: 'Admin',
    route: '/(admin)/finances',
    stateCount: 4,
    nav: 'admin',
    navFrom: ['admin'],
    navTo: ['admin'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-disputes',
    title: 'Admin Disputes',
    group: 'Admin',
    route: '/(admin)/disputes',
    stateCount: 4,
    nav: 'admin',
    navFrom: ['admin', 'admin-moderation'],
    navTo: ['admin-moderation'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-webhooks',
    title: 'Admin Webhooks',
    group: 'Admin',
    route: '/(admin)/webhooks',
    stateCount: 4,
    nav: 'admin',
    navFrom: ['admin'],
    navTo: ['admin-webhook-detail'],
    qaCycles: 2, qaScore: 12,
  },
  {
    id: 'admin-webhook-detail',
    title: 'Admin Webhook Detail',
    group: 'Admin',
    route: '/(admin)/webhooks/:id',
    stateCount: 3,
    nav: 'admin',
    navFrom: ['admin-webhooks'],
    navTo: ['admin-webhooks'],
    qaCycles: 2, qaScore: 12,
  },

  // ─── Brand ────────────────────────────────────────────────────────────────
  {
    id: 'components',
    title: 'UI Components',
    group: 'Brand',
    route: '/proto/states/components',
    stateCount: 10,
    nav: 'none',
  },
];
